### ISSUE TITLE
500 Error after filling survey form

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#78]
500 error when click on submitting survey form after filling the form completely. 

![screen shot 2017-02-15 at 12 06 37 am](https://cloud.githubusercontent.com/assets/13884387/22944514/bf715fd6-f312-11e6-9bde-e34996effa25.png)

**Comment by amir-qayyum-khan** [comment]
The issue is because you are already enroll (delete data from db but u are not unenroll) and trying to enroll again. need to handle enrollments efficiently

```python
Feb 14 19:06:30 ip-172-31-60-241 [service_variant=lms][django.request][env:sandbox] ERROR [ip-172-31-60-241  24238] [base.py:256] - Internal Server Error: /arbisoft_survey
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/student/views.py", line 645, in arbisoft_survey
    add_enrollment(user.username, course_id)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/enrollment/api.py", line 192, in add_enrollment
    return _data_api().create_course_enrollment(user_id, course_id, mode, is_active)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/enrollment/data.py", line 124, in create_course_enrollment
    raise CourseEnrollmentClosedError(err.message)
CourseEnrollmentClosedError
```

**Comment by aqdasrehman** [comment]
Fixed.
